server:
  port: 8081
spring:
  security:
    oauth2:
      client:

        registration:
          keycloak:
            client-id: VDB-KR
            client-secret: S0IAlcx5hI9WPFuEpgxNzyjxi7Aar6Y9
            redirect-uri: http://localhost:8081/login/oauth2/code/keyclock

        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/oauth2

#server:
#  port: 8081
#spring:
#  security:
#    oauth2:
#      client:           # Prefix
#
#        registration:   # Client Config (?????)
#          keycloak:     # OAuth2ClientProperties ? Registration(?????) ??? Key ??? ???? ?(Map). --> Client ?  ???? ?? Key ??? ???? ?.
#            authorization-grant-type: authorization_code                     # ?? ???????? ??? ???. (Authorization code grant, Implicit, client Credentials ??)
#            client-name: VDB-KR                                              # Client Name
#            client-id: VDB-KR                                                # Authorization Server ? ??? ????? ???.
#            client-secret: S0IAlcx5hI9WPFuEpgxNzyjxi7Aar6Y9                  # Client Secret Key
#            redirect-uri: http://localhost:8081/login/oauth2/code/keyclock   # ????? Code ? ???? ??. (????? ?????? ??? ?? ??? ?? ??.)
#            client-authentication-method: client_secret_post                 # Client ????? ?? ?? ??. (Access Token ? ???? clientid ? secret ? ?? ????? ? ??? CLient ? ????? ?? ??. ?? Client ?? ??? POST ? ? ?? ???.). Basic, Post, none ??? ??.
#            scope: openid,profile,email                                      # Resource ? ?? ?? ?? ??
#
#        provider:     ## Authorization Server Config (???)
#          keycloak:   # OAuth2ClientProperties ? Provider(?????) ??? Key ??? ???? ?(Map). --> provider ?  ???? ?? Key ??? ???? ?.
#            authorization-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/auth     # Authorization Grant Endpoint (??????(code) ? ???? Endpoint)
#            token-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/token            # AccessToken ? ??? Endpoint (Code ? AccessToken ? ??? ??.)
#            user-info-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/userinfo     # UserInfo ? ??? ? ?? EndPoint
#            issuer-uri: http://localhost:8080/realms/oauth2                                         # ??? ??? ?? (????? ???? ???? MetaData ? ??? ? ??.)
#            jwk-set-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs          # JwkSetUri EndPoint (Client ? Resource Server ?? ???? ???? ?? ??? AccessToken ? ???? ??? Public Key ? ?? ? ?? ??.)
#            user-name-attribute: preferred_username                                                 # OAuth2 ????? ???? Claim ? (Authorization Server ?? ??). (Google ? SUB)
